[user]
name = "Michael Kaiser"
email = "michael.kaiser@kiteit.de"

[ui]
default-command = "log"
editor = "vim"

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"